name: Precheck Backend

on:
  workflow_dispatch:     # manual trigger
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        required: false
        default: "3.13"
        type: string

jobs:
  precheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      ENV_TYPE: CI
      BASE_URL: ${{ secrets.BASE_URL }}
      GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          export PYTHONPATH=.
          pip install -r requirements.txt
          pytest utils/precheck.py::test_verify_backend_alive -v
